apiVersion: v1
kind: Service
metadata:
  name: gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-1:815280425737:certificate/dea9e12d-5659-4f13-ba38-4a77e4884999"
spec:
  loadBalancerIP:
  ports:
  - port: 80
    name: http
    # Use named container port.
    targetPort: 8080
  - port: 443
    name: https
    # Use named container port.
    targetPort: 8080
  selector:
    app: gateway
  type: LoadBalancer