apiVersion: v1
kind: Service
metadata:
  name: gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  loadBalancerIP:
  ports:
  - port: 80
    name: http
    # Use named container port.
    targetPort: 8080
  - port: 443
    name: https
    # Use named container port.
    targetPort: 8080
  selector:
    app: gateway
  type: LoadBalancer